name: Node.js CI

on:
  push:
    branches: [master]
    paths:
      - '**.js'

jobs:
  run-tests:
    strategy:
      matrix:
        node-version: ['16', '14']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Test
      run: npm run jest
        
    - name: Build Hamonize-connect
      run: npm run build:linux
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hamonize-connect
        path: ./hamonize-demo*.deb

   
