name: Hamonize CI
on:
  push:
    branches: [ master ]
jobs:          
  build-connect:
    name: Build Hamonize-demo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '14']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install debhelper npm
      
      - name: Install Dependencies
        run: npm ci  
        
      - name: Build Hamonize-demo
        run: npm run build:linux
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hamonize-demo_appimage
          path: ./hamonize-demo*.deb

          
